[package]
name = "licrypto"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["hypengw <hypengwip@gmail.com>"]

[lib]
name = "licrypto"
module = "licrypto"
archive = "licrypto"

[[test]]
name = "licrypto-tests"
sources = ["tests/base64.cpp", "tests/main.cpp", "tests/sha1.cpp", "tests/sha256.cpp", "tests/sha512.cpp"]

[profile]
exceptions = false
rtti = false

[dependencies]
rstd-std = { version = "0.1.0", pub = true }

[dev-dependencies]
rstd-test = { version = "0.1.0" }
