[package]
name = "licrypto"
version = "0.1.0"

[lib]
name = "licrypto"
module = "licrypto"
archive = "licrypto"
sources = ["src/lib.cppm"]

[[test]]
name = "licrypto-tests"
sources = ["tests/main.cpp", "tests/sha256.cpp"]

[profile]
exceptions = false
rtti = false

[dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"
visibility = "public"

[dev-dependencies.rstd-test]
git = "https://github.com/litocpp/rstd.git"
