[package]
name = "licrypto"
version = "0.1.0"

[lib]
name = "licrypto"
module = "licrypto"
archive = "licrypto"
sources = ["src/base64.cppm", "src/lib.cppm", "src/sha256.cppm", "src/sha512.cppm"]

[[test]]
name = "licrypto-tests"
sources = ["tests/base64.cpp", "tests/main.cpp", "tests/sha256.cpp", "tests/sha512.cpp"]

[profile]
exceptions = false
rtti = false

[dependencies]
rstd-std = { version = "0.1.0", visibility = "public" }

[dev-dependencies]
rstd-test = { version = "0.1.0" }
